# Generated by Django 6.0.6 on 2026-08-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of delivery attempts made so far.')),
                ('last_attempt_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent delivery attempt.', null=True)),
                ('recipient_to', models.TextField(help_text='Comma-separated list of recipient email addresses.')),
                ('recipient_cc', models.TextField(blank=True, help_text='Comma-separated list of CC addresses.', null=True)),
                ('recipient_bcc', models.TextField(blank=True, help_text='Comma-separated list of BCC addresses.', null=True)),
                ('subject', models.CharField(max_length=255)),
                ('message_body', models.TextField(help_text='Plain text or HTML content of the email.')),
                ('is_html', models.BooleanField(default=False, help_text='Designates whether the body contains HTML markup.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Stores traceback or error logs if sending fails.', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FrequentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly label shown in admin, e.g. 'Monthly Savings Reminder'.", max_length=100, unique=True)),
                ('category', models.CharField(choices=[('savings_deposit_howto', 'Reminder: How to Pay Savings Deposit'), ('share_capital_howto', 'Reminder: How to Pay Share Capital'), ('loan_repayment_howto', 'Reminder: How to Pay Loan'), ('loan_arrears', 'Reminder: Loan Arrears Notice'), ('loan_eligibility', 'Marketing: Loan Eligibility (best offer from pool)'), ('fixed_deposit_marketing', 'Marketing: Fixed Deposit Account'), ('share_capital_marketing', 'Marketing: Share Capital Below Minimum'), ('dormant_reactivation', 'Marketing: Dormant Account Reactivation'), ('happy_birthday', 'Marketing: Happy Birthday'), ('happy_holiday', 'Marketing: Happy Holiday'), ('mobile_loan_eligibility', 'Marketing: Mobile Loan Eligibility (deprecated)'), ('normal_loan_eligibility', 'Marketing: Normal Loan Eligibility (deprecated)')], db_index=True, help_text='Determines the audience and available placeholders.', max_length=40)),
                ('message_template', models.TextField(help_text='SMS body with placeholders: {first_name}, {paybill}, {account_no}, {loan_no}, {loan_balance}, {arrears}, {eligible_amount}, {sacco_name}, etc.')),
                ('balance_filter_min', models.DecimalField(blank=True, decimal_places=2, help_text="Optional: minimum account balance to target. For Fixed Deposit marketing: target members with savings ≥ this. For Share Capital marketing: overrides the product's min_balance.", max_digits=14, null=True)),
                ('balance_filter_max', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: maximum account balance to target.', max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to pause this notification without deleting it.')),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful generation run.', null=True)),
                ('last_run_count', models.PositiveIntegerField(default=0, help_text='Number of SMS queued during the last run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Frequent Notification',
                'verbose_name_plural': 'Frequent Notifications',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of delivery attempts made so far.')),
                ('last_attempt_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent delivery attempt.', null=True)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, help_text='Provider (Celcom Africa) messageid returned on success. Use with the DLR endpoint to query delivery status.', max_length=64, null=True)),
                ('provider_response_code', models.IntegerField(blank=True, help_text='Provider response-code from the last delivery attempt.', null=True)),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('customer_status', models.CharField(default='active', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('savings_deposit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('share_capital_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fixed_deposit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('savings_deposit_account', models.CharField(blank=True, max_length=30)),
                ('share_capital_account', models.CharField(blank=True, max_length=30)),
                ('fixed_deposit_account', models.CharField(blank=True, max_length=30)),
                ('has_active_loan', models.BooleanField(default=False)),
                ('active_loan_nos', models.TextField(blank=True, help_text='Comma-separated active loan numbers.')),
                ('active_loan_names', models.TextField(blank=True, help_text='Comma-separated product descriptions.')),
                ('active_loan_balances', models.TextField(blank=True, help_text='Comma-separated outstanding balances.')),
                ('active_loan_arrears', models.TextField(blank=True, help_text='Comma-separated arrears amounts.')),
                ('active_loan_installments', models.TextField(blank=True, help_text='Comma-separated monthly installment amounts.')),
                ('active_loan_accounts', models.TextField(blank=True, help_text='Comma-separated loan account codes.')),
                ('active_loan_account_types', models.TextField(blank=True, help_text='Comma-separated account_type of each active loan (e.g. normal_loan,mobile_loan). Used to suppress cross-selling a product the member already holds.')),
                ('total_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mobile_loan_eligible', models.BooleanField(default=False)),
                ('mobile_loan_max_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('normal_loan_eligible', models.BooleanField(default=False)),
                ('normal_loan_max_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('eligible_offers', models.JSONField(blank=True, default=list, help_text='Loan products the member qualifies for and does NOT already hold (top offers only). Authoritative source for marketing eligibility SMS.')),
                ('has_any_offer', models.BooleanField(db_index=True, default=False, help_text='True if eligible_offers is non-empty. Cheap filter for the marketing queue.')),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member Snapshot',
                'verbose_name_plural': 'Member Snapshots',
                'ordering': ['cust_no'],
                'indexes': [models.Index(fields=['customer_status', 'has_active_loan'], name='idx_snap_status_loan'), models.Index(fields=['dob'], name='idx_snap_dob'), models.Index(fields=['customer_status', 'has_any_offer'], name='idx_snap_offers'), models.Index(fields=['mobile_loan_eligible'], name='idx_snap_mobi_elig'), models.Index(fields=['normal_loan_eligible'], name='idx_snap_norm_elig')],
            },
        ),
    ]
