# Generated by Django 6.0.6 on 2026-08-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_hours', models.PositiveIntegerField(default=24)),
                ('email_recipient', models.EmailField(help_text='The email address that will receive the .sql backup file.', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('file_size', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChamaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='NODi Lite', max_length=255)),
                ('brand_footer', models.CharField(default='NODi Core Banking System ver.1.0', max_length=255)),
                ('chama_name', models.CharField(max_length=255)),
                ('chama_address', models.TextField()),
                ('chama_contact', models.CharField(max_length=50)),
                ('chama_location', models.CharField(max_length=255)),
                ('chama_footer', models.CharField(blank=True, default='NODi Core Banking System ver.2.0', max_length=255, null=True)),
                ('chama_logo', models.ImageField(blank=True, null=True, upload_to='chama_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chama Information',
                'verbose_name_plural': 'Chama Information',
            },
        ),
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('branch_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('timezone', models.CharField(default='EAT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Branch',
                'verbose_name_plural': 'Company Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short headline shown on the card.', max_length=120)),
                ('subtitle', models.CharField(blank=True, help_text='Optional second line.', max_length=255)),
                ('body', models.TextField(blank=True, help_text='Full message shown when tapped.')),
                ('image', models.ImageField(blank=True, help_text='Banner image, recommended 16:9 aspect (e.g. 1280x720).', null=True, upload_to='promotions/')),
                ('promo_type', models.CharField(choices=[('ad', 'Advertisement'), ('update', 'Service Update'), ('announcement', 'Announcement'), ('product', 'New Product')], default='ad', max_length=20)),
                ('cta_label', models.CharField(blank=True, help_text='Optional call-to-action label.', max_length=40)),
                ('cta_url', models.URLField(blank=True, help_text='Optional link the CTA opens.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower = shown earlier.')),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional schedule start.', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional schedule end.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
