# Generated by Django 6.0.6 on 2026-08-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvalrequest',
            new_name='approvals_a_status_81da33_idx',
            old_name='approvals_a_status_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalrequest',
            new_name='approvals_a_maker_i_4d85b1_idx',
            old_name='approvals_a_maker_idx',
        ),
    ]
