# Generated by Django 6.0.6 on 2026-08-17 13:44

import django.utils.timezone
import statements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatementHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(db_index=True, max_length=64, unique=True)),
                ('cust_no', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('account_code', models.CharField(max_length=50)),
                ('statement_type', models.CharField(choices=[('single', 'Single Account'), ('consolidated', 'Consolidated')], default='single', max_length=20)),
                ('generated_by', models.CharField(blank=True, max_length=150)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=statements.models._default_expiry)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StatementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StatementSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_month', models.PositiveIntegerField(default=28, help_text='Day of the month to send statements (1-28)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
