# Generated by Django 6.0.6 on 2026-08-17 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('accounts_clerk', 'Accounts Clerk'), ('loan_officer', 'Loan Officer'), ('manager', 'Manager'), ('admin', 'Admin')], default='accounts_clerk', max_length=20)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the Django admin site.')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions explicitly assigned without manual groups.')),
                ('device_id', models.CharField(blank=True, max_length=64, null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Consecutive failed login attempts. Resets on success.')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account locked until this timestamp due to excessive failed attempts.', null=True)),
                ('last_failed_login', models.DateTimeField(blank=True, help_text='Timestamp of the most recent failed login attempt.', null=True)),
                ('otp_abuse_locked', models.BooleanField(default=False, help_text='Account locked due to excessive unused/expired OTP requests.')),
                ('otp_abuse_locked_at', models.DateTimeField(blank=True, help_text='When OTP abuse lock was triggered.', null=True)),
                ('last_password_reset_request', models.DateTimeField(blank=True, help_text='Prevents rapid-fire password reset requests.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(db_index=True, max_length=150)),
                ('ip_address_hash', models.CharField(db_index=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Raw IP stored temporarily for active incident response; purged by cleanup job.', null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed_credentials', 'Failed - Bad Credentials'), ('failed_locked', 'Failed - Account Locked'), ('failed_inactive', 'Failed - Account Inactive'), ('failed_otp', 'Failed - Invalid OTP'), ('failed_rate_limited', 'Failed - Rate Limited'), ('success_otp', 'Success - OTP Login')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address_hash', 'timestamp'], name='accounts_lo_ip_addr_4c5611_idx'), models.Index(fields=['username_attempted', 'timestamp'], name='accounts_lo_usernam_e61b37_idx')],
            },
        ),
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_no', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset'), ('verification', 'Verification'), ('admin_login', 'Admin Login')], default='registration', max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('request_ip_hash', models.CharField(blank=True, default='', help_text='SHA-256 hash (truncated) of the requesting IP.', max_length=32)),
                ('user', models.ForeignKey(blank=True, help_text='Linked user (null for pre-registration OTPs).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'created_at'], name='accounts_ot_email_b47daa_idx'), models.Index(fields=['phone', 'purpose', 'created_at'], name='accounts_ot_phone_0bb485_idx'), models.Index(fields=['otp_code', 'email', 'is_used'], name='accounts_ot_otp_cod_b7757b_idx')],
            },
        ),
    ]
