# Generated by Django 6.0.6 on 2026-09-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_allowed_to_create_records',
            field=models.BooleanField(default=True, help_text='If False, user can only view data on the admin mobile app (read-only).'),
        ),
    ]
