# Generated by Django 6.0.6 on 2026-08-17 13:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccountsSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=10, unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('acc_initials', models.CharField(max_length=10, unique=True)),
                ('account_type', models.CharField(choices=[('share_capital', 'Share Capital'), ('welfare_deposit', 'Welfare Deposit'), ('seed_deposit', 'Seed Deposit'), ('repsi_loan', 'Repsi Loan'), ('normal_loan', 'Normal Loan')], max_length=50)),
                ('interest_calc_method', models.CharField(default='reducing_balance', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_loan_account', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DividendDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('withholding_tax_percent', models.DecimalField(decimal_places=2, default=15.0, help_text='Enter as a percentage, e.g., 15 for 15%', max_digits=5)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=100.0, help_text='Flat fee deducted per member payout', max_digits=10)),
                ('saving_type', models.CharField(default='share_capital', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InterestBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True)),
                ('saving_type', models.CharField(choices=[('share_capital', 'Share Capital'), ('welfare_deposit', 'Welfare Deposit'), ('seed_deposit', 'Seed Deposit')], max_length=50)),
                ('amount_to_share', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('wht_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cut_off_date', models.DateField()),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_net_payout', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_no', models.PositiveIntegerField(db_index=True)),
                ('loan_id', models.PositiveIntegerField(db_index=True)),
                ('loan_no', models.CharField(db_index=True, max_length=50, null=True)),
                ('loan_type', models.CharField(max_length=50)),
                ('tr_date', models.DateTimeField()),
                ('tr_ref', models.CharField(db_index=True, max_length=50)),
                ('ext_ref', models.CharField(db_index=True, max_length=50, null=True)),
                ('tr_desc', models.CharField(blank=True, max_length=255)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=50)),
                ('trans_id', models.CharField(max_length=30, unique=True)),
                ('trans_time', models.DateTimeField(max_length=30)),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('business_shortcode', models.CharField(max_length=20)),
                ('bill_ref_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('org_account_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('third_party_trans_id', models.CharField(blank=True, max_length=50, null=True)),
                ('msisdn', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('posted', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_no', models.PositiveIntegerField(db_index=True)),
                ('saving_type', models.CharField(max_length=50)),
                ('tr_date', models.DateTimeField()),
                ('tr_ref', models.CharField(db_index=True, max_length=50)),
                ('ext_ref', models.CharField(db_index=True, max_length=50, null=True)),
                ('tr_desc', models.CharField(blank=True, max_length=255)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BulkUploadQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('saving_type', models.CharField(max_length=50)),
                ('loan_id', models.PositiveIntegerField(db_index=True)),
                ('loan_no', models.CharField(db_index=True, max_length=50, null=True)),
                ('loan_type', models.CharField(max_length=50, null=True)),
                ('is_loan', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DividendDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_weight', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_dividend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_dividend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='transactions.dividenddeclaration')),
            ],
        ),
        migrations.CreateModel(
            name='InterestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_no', models.PositiveIntegerField()),
                ('member_name', models.CharField(max_length=255)),
                ('weighted_avg_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gross_interest', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('withholding_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_payout', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_posted', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transactions.interestbatch')),
            ],
        ),
        migrations.CreateModel(
            name='DividendSlipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField()),
                ('savings_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ratio', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('weighted_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_interest', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_interest', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip_items', to='transactions.interestdetail')),
            ],
            options={
                'ordering': ['period_date'],
            },
        ),
        migrations.CreateModel(
            name='PostedMpesaNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_no', models.CharField(max_length=20)),
                ('account_type', models.CharField(max_length=30)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mpesa_notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.mpesanotification')),
            ],
        ),
    ]
