# Generated by Django 6.0.6 on 2026-08-19 09:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_saccoaccountsledger_ledger_acct_date_id_idx_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTransactionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('label', models.CharField(blank=True, help_text="Optional user-given name, e.g. 'June deposits batch 2'", max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('posted', 'Posted'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('grid_data', models.JSONField(default=list, help_text='Full grid state — array of row dicts for resume')),
                ('bank_account_id', models.PositiveIntegerField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bulk Transaction Batch',
                'verbose_name_plural': 'Bulk Transaction Batches',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DividendDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_no', models.CharField(max_length=20)),
                ('member_name', models.CharField(max_length=255)),
                ('weighted_avg_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gross_interest', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('withholding_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_payout', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_posted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DividendTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('calculation', 'Calculation'), ('posting', 'Posting')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('current_chunk', models.PositiveIntegerField(default=0)),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('saving_type', models.CharField(blank=True, max_length=50)),
                ('calc_params', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuarantinedMpesaPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField(help_text='IP that sent this payload')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_body', models.TextField(help_text='Full raw request body (JSON)')),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('xff_header', models.CharField(blank=True, help_text='X-Forwarded-For header value', max_length=500)),
                ('request_path', models.CharField(blank=True, max_length=200)),
                ('trans_id', models.CharField(blank=True, db_index=True, max_length=30)),
                ('trans_amount', models.CharField(blank=True, max_length=30)),
                ('msisdn', models.CharField(blank=True, max_length=200)),
                ('bill_ref_number', models.CharField(blank=True, max_length=100)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('legitimate', 'Legitimate — Promoted'), ('suspicious', 'Suspicious — Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Quarantined M-Pesa Payload',
                'verbose_name_plural': 'Quarantined M-Pesa Payloads',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('charge_method', models.CharField(choices=[('flat', 'Flat Amount (KES)'), ('percentage', 'Percentage')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('applies_to', models.CharField(choices=[('on_principal', 'On withdrawal amount'), ('on_charge', 'On the band fee')], default='on_charge', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction Charge',
                'verbose_name_plural': 'Transaction Charges',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalChargeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Withdrawal Charge Band',
                'verbose_name_plural': 'Withdrawal Charge Bands',
                'ordering': ['from_amount'],
            },
        ),
        migrations.RemoveField(
            model_name='dividenddistribution',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='dividenddistribution',
            name='declaration',
        ),
        migrations.RemoveField(
            model_name='interestdetail',
            name='batch',
        ),
        migrations.RenameModel(
            old_name='InterestBatch',
            new_name='DividendBatch',
        ),
        migrations.AddField(
            model_name='bulkuploadqueue',
            name='account_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulkuploadqueue',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.saccoaccount'),
        ),
        migrations.AddField(
            model_name='customeraccountssetup',
            name='access_on_channels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeraccountssetup',
            name='base_deposits',
            field=models.ManyToManyField(blank=True, help_text="Loan products only: the savings products a member must hold to qualify for this loan. Their balances are combined with each product's loan_multiplier to compute eligibility.", limit_choices_to={'is_active': True, 'is_loan_account': False}, related_name='eligible_loan_products', to='transactions.customeraccountssetup'),
        ),
        migrations.AddField(
            model_name='customeraccountssetup',
            name='guarantee_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Savings only: how many times its face value this deposit may guarantee (e.g. 3 → KES 10k can guarantee up to KES 30k).', max_digits=5),
        ),
        migrations.AddField(
            model_name='customeraccountssetup',
            name='is_mobile_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeraccountssetup',
            name='is_withdrawable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeraccountssetup',
            name='loan_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text="Savings only: multiplier used to derive the owner's own borrowing capacity from this deposit balance (e.g. 5 → KES 20k gives eligibility up to KES 100k).", max_digits=5),
        ),
        migrations.AddField(
            model_name='customeraccountssetup',
            name='max_loan_limit',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customeraccountssetup',
            name='max_repayment_period',
            field=models.PositiveBigIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='customeraccountssetup',
            name='min_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customeraccountssetup',
            name='sacco_cash_account',
            field=models.ForeignKey(blank=True, help_text='The cash/bank GL account to hit on the other side of the journal. Usually 900-601001 Coop Bank. If blank, defaults to GL.CASH (900-601001).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_products', to='accounting.saccoaccount', verbose_name='GL Cash/Bank Account'),
        ),
        migrations.AddField(
            model_name='customeraccountssetup',
            name='sacco_gl_account',
            field=models.ForeignKey(blank=True, help_text="The GL account where this product's balance lives. Savings → a liability (e.g. 900-802000 Member Deposits). Loans → an asset (e.g. 900-630011 Repsi Loan).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_products', to='accounting.saccoaccount', verbose_name='GL Balance Account'),
        ),
        migrations.AddField(
            model_name='customeraccountssetup',
            name='sacco_interest_account',
            field=models.ForeignKey(blank=True, help_text='For loan products: the GL income account for interest (e.g. 900-110000 Normal Loan Interest). Leave blank for savings products.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interest_products', to='accounting.saccoaccount', verbose_name='GL Interest Income Account'),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='account_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postedmpesanotification',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='account_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customeraccountssetup',
            name='account_type',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='loantransaction',
            name='cust_no',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='mpesanotification',
            name='trans_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='postedmpesanotification',
            name='mpesa_notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posting_details', to='transactions.mpesanotification'),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='cust_no',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='savingstransaction',
            index=models.Index(fields=['cust_no', 'saving_type'], name='idx_sav_cust_type'),
        ),
        migrations.AddIndex(
            model_name='savingstransaction',
            index=models.Index(fields=['saving_type', 'tr_date'], name='idx_sav_type_date'),
        ),
        migrations.AddIndex(
            model_name='savingstransaction',
            index=models.Index(fields=['saving_type', 'tr_date', 'cust_no'], name='idx_sav_type_date_cust'),
        ),
        migrations.AddField(
            model_name='bulktransactionbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dividenddetail',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transactions.dividendbatch'),
        ),
        migrations.AlterField(
            model_name='dividendslipitem',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip_items', to='transactions.dividenddetail'),
        ),
        migrations.AddField(
            model_name='dividendtaskprogress',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='transactions.dividendbatch'),
        ),
        migrations.AddField(
            model_name='transactioncharge',
            name='sacco_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.saccoaccount'),
        ),
        migrations.DeleteModel(
            name='DividendDistribution',
        ),
        migrations.AddIndex(
            model_name='dividenddetail',
            index=models.Index(fields=['batch', 'is_posted'], name='idx_divdetail_batch_posted'),
        ),
        migrations.AddIndex(
            model_name='dividenddetail',
            index=models.Index(fields=['cust_no', 'batch'], name='idx_divdetail_cust_batch'),
        ),
        migrations.DeleteModel(
            name='InterestDetail',
        ),
    ]
