# Generated by Django 6.0.6 on 2026-08-17 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_no', models.CharField(blank=True, editable=False, help_text='Auto-generated zero-padded member number (e.g. 00001).', max_length=20, unique=True)),
                ('customer_type', models.CharField(choices=[('adult_individual', 'Adult-Individual'), ('minor_individual', 'Minor-Individual'), ('group', 'Group'), ('church', 'Church')], default='adult_individual', max_length=40)),
                ('full_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single'), ('Separated', 'Separated'), ('Un-known', 'Un-known')], max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('home_address', models.CharField(blank=True, max_length=255, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('kra_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('reg_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reg_fee_is_paid', models.BooleanField(default=False)),
                ('default_notifications_setting', models.BooleanField(default=False)),
                ('temp_notifications_setting', models.BooleanField(blank=True, null=True)),
                ('is_treasury', models.BooleanField(default=False)),
                ('customer_status', models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('exited', 'Exited'), ('deceased', 'Deceased'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('exit_reason', models.TextField(blank=True, null=True)),
                ('is_reactivated', models.BooleanField(default=False)),
                ('reactivation_date', models.DateField(blank=True, null=True)),
                ('reactivation_reason', models.TextField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='administration.companybranch')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_customers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['cust_no'],
            },
        ),
        migrations.CreateModel(
            name='CustomerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_members', models.IntegerField(default=0)),
                ('churches', models.IntegerField(default=0)),
                ('groups', models.IntegerField(default=0)),
                ('male', models.IntegerField(default=0)),
                ('female', models.IntegerField(default=0)),
                ('age_18_35', models.IntegerField(default=0)),
                ('age_35_50', models.IntegerField(default=0)),
                ('age_50_60', models.IntegerField(default=0)),
                ('age_above_70', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('dormant', models.IntegerField(default=0)),
                ('deceased', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Statistics',
                'verbose_name_plural': 'Customer Statistics',
            },
        ),
        migrations.CreateModel(
            name='CustomerEconomicActivity',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='economic_activity', serialize=False, to='customers.customer')),
                ('employment_status', models.CharField(choices=[('self_employed', 'Self-Employed'), ('employed', 'Employed')], max_length=20)),
                ('economic_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Customer Economic Activity',
                'verbose_name_plural': 'Customer Economic Activities',
            },
        ),
        migrations.CreateModel(
            name='ChurchOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churchofficials', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Church Official',
                'verbose_name_plural': 'Church Officials',
            },
        ),
        migrations.CreateModel(
            name='GroupOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupofficials', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Group Official',
                'verbose_name_plural': 'Group Officials',
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kin_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('kin_relationship', models.CharField(choices=[('Son', 'Son'), ('Daughter', 'Daughter'), ('Parent', 'Parent'), ('Spouse', 'Spouse'), ('Other', 'Other')], max_length=100)),
                ('kin_dob', models.DateField(blank=True, null=True)),
                ('kin_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('kin_national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kins', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Next of Kin',
                'verbose_name_plural': 'Next of Kin',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_status'], name='idx_customer_status'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='idx_customer_phone'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['national_id'], name='idx_customer_nid'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['reg_email'], name='idx_customer_email'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('cust_no__regex', '^[0-9]{5}$'), ('cust_no__regex', '^[1-9][0-9]{5,19}$'), _connector='OR'), name='strict_cust_no_padding_check'),
        ),
    ]
