# Generated by Django 6.0.6 on 2026-06-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='audit_secur_event_6ce141_idx',
            old_name='audit_secur_event_e1ee9a_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='audit_secur_actor_734f63_idx',
            old_name='audit_secur_actor_b5e0d2_idx',
        ),
    ]
