# Generated by Django 6.0.6 on 2026-08-17 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('charge_type', models.CharField(choices=[('flat_amount', 'Flat Amount'), ('percentage', 'Percentage')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunningLoanStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(max_length=50, unique=True)),
                ('application_date', models.DateField()),
                ('posting_date', models.DateField()),
                ('repayment_start_date', models.DateField()),
                ('last_repayment_date', models.DateTimeField(blank=True, null=True)),
                ('next_repayment_date', models.DateField(blank=True, null=True)),
                ('installments', models.IntegerField()),
                ('repayment_end_date', models.DateField()),
                ('cust_no', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=255, null=True)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('loan_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('repayment_method', models.CharField(default='Flat Rate', max_length=50)),
                ('principle_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('principle_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interest_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('defaulted_days', models.IntegerField(default=0)),
                ('total_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('principle_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_interest_charge', models.DateField(blank=True, null=True)),
                ('interest_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('defaulted_installments', models.IntegerField(default=0)),
                ('loan_classification', models.CharField(max_length=50)),
                ('sales_person', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_account', models.CharField(max_length=50)),
                ('disbursed', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=150)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('loan_status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Running Loan Stats',
            },
        ),
        migrations.CreateModel(
            name='InterestChargeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=50)),
                ('target_date', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calc_method_used', models.CharField(default='reducing_balance', max_length=50)),
                ('total_interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft Preview'), ('posted', 'Posted / Finalized')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('loan_type', 'target_date', 'status')},
            },
        ),
        migrations.CreateModel(
            name='InterestChargeDraftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField()),
                ('loan_no', models.CharField(max_length=50)),
                ('cust_no', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=150)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('calculated_interest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_items', to='loans.interestchargebatch')),
            ],
        ),
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(editable=False, max_length=15, null=True, unique=True)),
                ('loan_date', models.DateField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_period', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('net_disbursed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='cust_no', on_delete=django.db.models.deletion.CASCADE, to='customers.customer', to_field='cust_no')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.customeraccountssetup')),
            ],
        ),
        migrations.CreateModel(
            name='LoanChargeRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_charge_recoveries', to='loans.loancharge')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanhistory')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('guarantor_cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees_given', to='customers.customer')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanhistory')),
            ],
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_type', models.CharField(choices=[('land', 'Land / Title Deed'), ('vehicle', 'Motor Vehicle / Logbook'), ('other', 'Other Asset')], max_length=20)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forced_sale_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mortgage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('insurance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('title_deed_no', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, help_text='e.g. 0.05 Ha', max_length=50, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True)),
                ('chassis_no', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('owner', models.ForeignKey(help_text='Owner of the asset (usually the borrower)', on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='loans.loanhistory')),
            ],
        ),
    ]
