# Generated by Django 6.0.3 on 2026-06-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanLimitGraduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_no', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('loan_product', models.CharField(max_length=50)),
                ('graduation_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.AlterField(
            model_name='loanhistory',
            name='loan_no',
            field=models.CharField(editable=False, max_length=40, null=True, unique=True),
        ),
    ]
