# Generated by Django 6.0.3 on 2026-06-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanlimitgraduation_alter_loanhistory_loan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanlimitgraduation',
            name='cust_no',
            field=models.PositiveBigIntegerField(),
        ),
    ]
