# Generated by Django 6.0.3 on 2026-06-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loanlimitgraduation_cust_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhistory',
            name='disbursal_ref',
            field=models.CharField(editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loanhistory',
            name='disbursed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loanhistory',
            name='is_disbursed',
            field=models.BooleanField(default=False),
        ),
    ]
