# Generated by Django 6.0.3 on 2026-06-08 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanhistory_disbursal_ref_loanhistory_disbursed_at_and_more'),
        ('transactions', '0002_bulktransactionbatch_dividenddetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancharge',
            name='loan_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.customeraccountssetup'),
        ),
    ]
