# Generated by Django 6.0.6 on 2026-06-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loancharge_loan_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanchargerecovery',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanchargerecovery',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='loanchargerecovery',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
