# Generated by Django 6.0.6 on 2026-06-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loanchargerecovery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanlimitgraduation',
            name='cust_no',
            field=models.CharField(max_length=40),
        ),
    ]
