# Generated by Django 6.0.6 on 2026-06-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_loanlimitgraduation_cust_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhistory',
            name='is_restructured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanhistory',
            name='original_loan_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='loanhistory',
            name='restructure_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loanhistory',
            name='restructured_at',
            field=models.DateTimeField(null=True),
        ),
    ]
