# Generated by Django 6.0.6 on 2026-06-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_loanhistory_is_restructured_and_more'),
        ('transactions', '0002_bulktransactionbatch_dividenddetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loancharge',
            name='loan_product',
        ),
        migrations.AddField(
            model_name='loancharge',
            name='loan_products',
            field=models.ManyToManyField(blank=True, help_text='Select all loan products that attract this charge.', limit_choices_to={'is_loan_account': True}, related_name='loan_charges', to='transactions.customeraccountssetup'),
        ),
    ]
