# Generated by Django 6.0.6 on 2026-06-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_remove_loancharge_loan_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhistory',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
