# Generated by Django 6.0.6 on 2026-06-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_loanhistory_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhistory',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanhistory',
            name='approved_by',
            field=models.CharField(blank=True, null=True),
        ),
    ]
