# Generated by Django 6.0.6 on 2026-06-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('loans', '0011_loanhistory_approved_at_loanhistory_approved_by'),
        ('transactions', '0002_bulktransactionbatch_dividenddetail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanhistory',
            options={'verbose_name_plural': 'Loan Histories'},
        ),
        migrations.AlterField(
            model_name='loanhistory',
            name='approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='loanhistory',
            index=models.Index(fields=['is_approved', 'is_disbursed'], name='idx_loan_pipeline'),
        ),
        migrations.AddIndex(
            model_name='loanhistory',
            index=models.Index(fields=['customer', 'is_disbursed'], name='idx_cust_active_loans'),
        ),
        migrations.AddIndex(
            model_name='loanhistory',
            index=models.Index(fields=['loan_date'], name='idx_loan_date_sort'),
        ),
    ]
