# Generated by Django 6.0.6 on 2026-06-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_alter_loanhistory_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='runningloanstat',
            index=models.Index(fields=['cust_no', 'product_code', 'loan_status'], name='idx_run_cust_status'),
        ),
        migrations.AddIndex(
            model_name='runningloanstat',
            index=models.Index(fields=['loan_status', 'next_repayment_date'], name='idx_run_billing_schedule'),
        ),
        migrations.AddIndex(
            model_name='runningloanstat',
            index=models.Index(fields=['loan_classification', 'loan_balance', 'total_arrears'], name='idx_run_risk_arrears'),
        ),
    ]
