# Generated by Django 6.0.6 on 2026-06-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('loans', '0013_runningloanstat_idx_run_cust_status_and_more'),
        ('transactions', '0002_bulktransactionbatch_dividenddetail_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loanhistory',
            name='idx_cust_active_loans',
        ),
        migrations.AddIndex(
            model_name='loanhistory',
            index=models.Index(fields=['customer', 'loan_no', 'is_disbursed'], name='idx_cust_active_loans'),
        ),
    ]
