# Generated by Django 6.0.6 on 2026-07-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_loan_defaulter_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancharge',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loancharge',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
