# Generated by Django 6.0.6 on 2026-07-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_loancharge_max_amount_loancharge_min_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanhistory',
            name='insurance_fee',
        ),
        migrations.RemoveField(
            model_name='loanhistory',
            name='other_charges',
        ),
        migrations.RemoveField(
            model_name='loanhistory',
            name='processing_fee',
        ),
        migrations.AddField(
            model_name='loancharge',
            name='is_bridging_fee',
            field=models.BooleanField(default=False),
        ),
    ]
