# Generated by Django 6.0.6 on 2026-07-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_remove_loanhistory_insurance_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhistory',
            name='offset_data',
            field=models.JSONField(blank=True, default=list, help_text='[{"loan_no":"LN000123","amount":"50000.00"}, …]'),
        ),
        migrations.AddField(
            model_name='loanhistory',
            name='total_offset_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
