# Generated by Django 6.0.6 on 2026-09-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_loan_no_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanhistory',
            name='upfront_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
