# Generated by Django 6.0.6

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('loan_disburse', 'Loan Disbursement'), ('cheque_issue', "Banker's Cheque Issue"), ('bulk_post', 'Bulk Transaction Post'), ('interest_post', 'Interest Batch Post'), ('dividend_post', 'Dividend Posting'), ('journal_voucher', 'Journal Voucher'), ('income_entry', 'Income Entry'), ('expense_entry', 'Expense Entry'), ('member_exit', 'Member Exit'), ('account_setup', 'Account Setup Change'), ('fund_transfer', 'Inter-Account Fund Transfer')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_checked', to=settings.AUTH_USER_MODEL)),
                ('maker_note', models.TextField(blank=True)),
                ('checker_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict, help_text='Snapshot of submitted data for audit trail.')),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
