# Generated by Django 6.0.6 on 2026-08-19 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'action_type'], name='approvals_a_status_81da33_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['maker'], name='approvals_a_maker_i_4d85b1_idx'),
        ),
    ]
