# Generated by Django 6.0.6 on 2026-08-17 13:44

import accounting.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('day_of_month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoreBankingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('document_no', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('member_no', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.CharField(max_length=100)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JournalVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=30, unique=True)),
                ('voucher_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('rejected', 'Rejected')], default='draft', max_length=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalVoucherDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('voucher_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('grid_data', models.JSONField(default=list)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Journal Voucher Draft',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('entry_type', models.CharField(choices=[('sacco', 'SACCO GL Account'), ('customer', 'Customer Member Account')], default='sacco', max_length=10)),
                ('member_account_ref', models.CharField(blank=True, help_text="For customer lines: the specific member product account. Savings/deposits: '<acc_initials>-<cust_no>'. Loans: the loan_no (e.g. LN000037).", max_length=50)),
                ('member_loan_no', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=30)),
                ('completion_time', models.DateTimeField(db_index=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('account', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('paybill', 'Pay Bill Payment'), ('paybill_charge', 'Pay Bill Charge'), ('b2c_payment', 'B2C Disbursement'), ('b2c_charge', 'B2C Payment Charge'), ('bank_withdrawal', 'Withdrawal to Bank'), ('merchant_pay', 'Merchant Payment'), ('fsi_interop', 'FSI Interoperability'), ('other', 'Other')], default='other', max_length=20)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-completion_time'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('match_start', models.DateField()),
                ('match_end', models.DateField()),
                ('total_statement', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('unmatched_stmt', models.IntegerField(default=0)),
                ('unmatched_system', models.IntegerField(default=0)),
                ('charges_posted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('b2c_posted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('performed_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('adult_individual', 'Adult-Individual'), ('minor_individual', 'Minor-Individual'), ('group', 'Group'), ('church', 'Church')], max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaccoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=10, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_group', models.CharField(blank=True, choices=[('Income', 'Income'), ('Expenditure', 'Expenditure'), ('Fixed Asset', 'Fixed Asset'), ('Fixed Assets', 'Fixed Assets'), ('Current Asset', 'Current Asset'), ('Current Assets', 'Current Assets'), ('Current Liability', 'Current Liability'), ('Current Liabilities', 'Current Liabilities'), ('Long Term Liability', 'Long Term Liability'), ('Long Term Liabilities', 'Long Term Liabilities'), ('Equity', 'Equity'), ('Other', 'Other')], max_length=50, null=True)),
                ('is_cash_account', models.BooleanField(default=False, help_text='Mark if this is a cash/bank account for cash book tracking')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaccoAccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='SaccoAccountsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Transaction date — set to voucher date for JVs, completion_time for M-Pesa, or today for real-time entries.')),
                ('reference', models.CharField(max_length=100)),
                ('external_reference', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaccoExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('expense_date', models.DateTimeField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('reconciliation_status', models.CharField(choices=[('unreconciled', 'Unreconciled'), ('reconciled', 'Reconciled')], default='unreconciled', max_length=15)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_file', models.FileField(blank=True, null=True, upload_to=accounting.models.upload_to)),
                ('reconciliation_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('reconciliation_file', models.FileField(blank=True, null=True, upload_to=accounting.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=15)),
                ('is_posted_to_gl', models.BooleanField(default=False, help_text='True once the GL journal entry has been created.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaccoIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('income_date', models.DateTimeField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('reconciliation_status', models.CharField(choices=[('unreconciled', 'Unreconciled'), ('reconciled', 'Reconciled')], default='unreconciled', max_length=15)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('income_file', models.FileField(blank=True, null=True, upload_to=accounting.models.upload_to)),
                ('reconciliation_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('reconciliation_file', models.FileField(blank=True, null=True, upload_to=accounting.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=15)),
                ('is_posted_to_gl', models.BooleanField(default=False, help_text='True once the GL journal entry has been created.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomatedReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('automated_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounting.automatedreport')),
            ],
        ),
    ]
