# Generated by Django 6.0.6 on 2026-08-17 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('customers', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalvoucher',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_vouchers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalvoucher',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_vouchers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalvoucherdraft',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalvoucherline',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='journalvoucherline',
            name='member_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jv_lines', to='transactions.customeraccountssetup'),
        ),
        migrations.AddField(
            model_name='journalvoucherline',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalvoucher'),
        ),
        migrations.AddField(
            model_name='mpesarecord',
            name='upload_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_records', to='accounting.reconciliationlog'),
        ),
        migrations.AddField(
            model_name='saccoaccount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sacco_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saccoaccount',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sacco_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalvoucherline',
            name='sacco_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.saccoaccount'),
        ),
        migrations.AddField(
            model_name='saccoaccountbalance',
            name='sacco_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='accounting.saccoaccount'),
        ),
        migrations.AddField(
            model_name='saccoaccountsledger',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_sacco_account_ledgers', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='saccoaccountsledger',
            name='sacco_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.saccoaccount'),
        ),
        migrations.AddField(
            model_name='saccoexpense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saccoexpense',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_expenses', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='saccoexpense',
            name='reconciliation_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_expenses', to='accounting.saccoaccount'),
        ),
        migrations.AddField(
            model_name='saccoexpense',
            name='sacco_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounting.saccoaccount'),
        ),
        migrations.AddField(
            model_name='saccoexpense',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saccoincome',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saccoincome',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_incomes', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='saccoincome',
            name='reconciliation_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_incomes', to='accounting.saccoaccount'),
        ),
        migrations.AddField(
            model_name='saccoincome',
            name='sacco_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='accounting.saccoaccount'),
        ),
        migrations.AddField(
            model_name='saccoincome',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mpesarecord',
            unique_together={('receipt_no', 'category')},
        ),
        migrations.AddIndex(
            model_name='saccoaccountsledger',
            index=models.Index(fields=['sacco_account', 'date', 'id'], name='ledger_acct_date_id_idx'),
        ),
        migrations.AddIndex(
            model_name='saccoaccountsledger',
            index=models.Index(fields=['date'], name='ledger_date_idx'),
        ),
        migrations.AddIndex(
            model_name='saccoaccountsledger',
            index=models.Index(fields=['reference'], name='ledger_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='saccoaccountsledger',
            index=models.Index(fields=['external_reference'], name='ledger_extref_idx'),
        ),
    ]
