# Generated by Django 6.0.6 on 2026-08-19 09:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='saccoaccountsledger',
            name='ledger_acct_date_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='saccoaccountsledger',
            name='ledger_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='saccoaccountsledger',
            name='ledger_reference_idx',
        ),
        migrations.RemoveIndex(
            model_name='saccoaccountsledger',
            name='ledger_extref_idx',
        ),
        migrations.AlterUniqueTogether(
            name='mpesarecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='saccoaccount',
            name='is_cash_account',
        ),
        migrations.RemoveField(
            model_name='saccoexpense',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='saccoexpense',
            name='is_posted_to_gl',
        ),
        migrations.RemoveField(
            model_name='saccoincome',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='saccoincome',
            name='is_posted_to_gl',
        ),
        migrations.AlterField(
            model_name='mpesarecord',
            name='receipt_no',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesarecord',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saccoaccount',
            name='account_group',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saccoaccountsledger',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sacco_accounts_ledgers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saccoaccountsledger',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saccoaccountsledger',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sacco_accounts_ledgers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='saccoaccountsledger',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mpesarecord',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mpesarecord',
            name='is_reconciled',
        ),
        migrations.RemoveField(
            model_name='mpesarecord',
            name='reconciled_at',
        ),
        migrations.RemoveField(
            model_name='mpesarecord',
            name='upload_batch',
        ),
        migrations.DeleteModel(
            name='ReconciliationLog',
        ),
    ]
