# Generated by Django 6.0.6 on 2026-08-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_saccoaccountsledger_ledger_acct_date_id_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccoaccount',
            name='is_cash_account',
            field=models.BooleanField(default=False, help_text='Mark if this is a cash/bank account for cash book tracking'),
        ),
    ]
