# Generated by Django 6.0.6 on 2026-09-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_saccoaccount_is_cash_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccoaccount',
            name='show_on_admin_app',
            field=models.BooleanField(default=True, help_text='If True, this GL account appears in admin mobile app journal voucher selectors.'),
        ),
    ]
